/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.android.instrumentation.coil

import coil.intercept.Interceptor
import coil.request.ImageResult
import io.opentelemetry.extension.kotlin.asContextElement
import kotlinx.coroutines.withContext

/**
 * A Coil [Interceptor] that propagates the OTel "image.load" span into the Coil background
 * coroutine context.
 *
 * This interceptor bridges the gap between [CoilOtelEventListener] (which runs on the main thread
 * and creates the span) and the OkHttp background network fetcher. By wrapping the downstream
 * chain execution in `withContext(span.asContextElement())`, it guarantees that any spans
 * generated by OkHttp's instrumentation will correctly parent themselves to the `image.load` span.
 *
 * Call `addInterceptor` alongside `eventListenerFactory` during ImageLoader construction:
 * ```kotlin
 * val imageLoader = ImageLoader.Builder(context)
 *     .eventListenerFactory(VunetCoilEventListenerFactory())
 *     .components {
 *         add(VunetCoilInterceptor())
 *     }
 *     .build()
 * ```
 */
class VunetCoilInterceptor : Interceptor {
    override suspend fun intercept(chain: Interceptor.Chain): ImageResult {
        // Defensive: telemetry lookup failures must never break the image pipeline. Note the
        // lookup keys on the identity of chain.request — if another interceptor rebuilt the
        // request before this one runs, the lookup misses and OkHttp spans lose their parent,
        // so register this interceptor FIRST (see README).
        val contextElement =
            try {
                val key = System.identityHashCode(chain.request)
                CoilSpanStore.spans[key]?.asContextElement()
            } catch (_: Throwable) {
                null
            }

        return if (contextElement != null) {
            // Propagate the exact span from the EventListener into the coroutine context.
            // The OTel OkHttp instrumentation captures this automatically during newCall.
            withContext(contextElement) {
                chain.proceed(chain.request)
            }
        } else {
            chain.proceed(chain.request)
        }
    }
}
